### ISSUE TITLE
scheduler mode and curses

### ISSUE THREAD

**Issue by dr1s** [winiciuscota/OG-Bot#14]
I was thinking it might be useful to build a scheduler around the bot, so there is no need for cronjobs or anything and the daemon could be managed by something like supervisor, if it should fail.
This way we could also continuously check resources and it might be an option to build a bot to save the fleet.

That got me thinking if a simple curses ui (I always wanted  to learn how to do it but was never eager enough) would be a nice thing to have.
This way it would be cleaner and you have a lot more information, opposed to looking at the output of the terminal.

@winiciuscota What are you're thoughts on this?

Just an idea and it will probably take some time to implement.

**Comment by winiciuscota** [comment]
I use a free host service with a scheduler plugin to run the bot. I have this setup for almost a year now.

It would indeed be much better(easier to setup and change settings later on) if the bot had a scheduler builtin but I'm not familiar to the method you described, so I don't know how much work it would require to implement it. Maybe quartz would be better?

If you are eager enough to learn it now then it might be a good idea, but keep in mind that the bot must be still be able to operate in the current way

**Comment by dr1s** [comment]
Quartz is only available on Java afaik.
I was looking at [python sched](https://docs.python.org/2/library/sched.html) and it seems to do the trick.
There seems to be a problem with multithreading and queueing, but that doesn't concern us.
Another option would be to use threading.timer, but to implement this the bot needs a lot of work.

So far it was just an idea, i maybe try to get something running later.
Also it might take some time for me to accomplish this, as i will be traveling a lot in the next months.

**Comment by dr1s** [comment]
I implemented a basic schedular, but it needs some improvement.
https://github.com/dr1s/OG-Bot/tree/scheduler
