### ISSUE TITLE
Syntax Error: invalid syntax

### ISSUE THREAD

**Issue by Nubanzi** [winiciuscota/OG-Bot#18]
Worked fine this morning but now it sometimes failes with above error. Logs and Config is attached. Investigating the Problem but I could need some help :/
[user.cfg.txt](https://github.com/winiciuscota/OG-Bot/files/652181/user.cfg.txt)
[log.txt](https://github.com/winiciuscota/OG-Bot/files/652183/log.txt)

**Comment by winiciuscota** [comment]
That also happened to me sometimes. I believe that the cause of the error is that sometimes the server retrieves corrupted or invalid html files that beautifulsoup can't parse. I'll probably modify the bot to make new requests when that happens
